### ISSUE TITLE
Add sphinx-favicon

### ISSUE THREAD

**Issue by tcmetzger** [humitos/sphinx-extensions#16]
I recently created [this Sphinx extension](https://github.com/tcmetzger/sphinx-favicon) that allows you to add custom favicons. With `sphinx-favicon`, you can define favicons directly in `conf.py`, with different rel attributes such as `"icon"` or `"apple-touch-icon"` and any favicon size.

@astrojuanlu has suggested I mention this extension here - I'd love to see it included in your list of Sphinx extensions!

**Comment by humitos** [comment]
Hi @tcmetzger! Would you like to open a PR to add this extension following the current structure the others are following? 💪🏼
